### ISSUE TITLE
Generate settings.override.php

### ISSUE THREAD

**Issue by skounis** [skounis/toolkit#1]
The `drupal:settings-setup` command should be able to generate the `settings.override.php` file by respecting related entries in the `robo.yml` 

For project working with tha latest version `2.x` of `oe_theme` SparQL and a connection to it are required. It is handy during development to inject the connection details into the `settings.override`. 

## Example 
runner.yml
```
drupal:
  root: "web"
  base_url: ${env.DRUPAL_BASE_URL}
  sparql:
    host: "sparql"
    port: "8890"  
  site:
    profile: "oe_profile"
    name: "Cybersecurity Atlas"
    generate_db_url: false
    settings_override_file: "settings.override.php"
  account:
    name: ${env.DRUPAL_ACCOUNT_USERNAME}
    password: ${env.DRUPAL_ACCOUNT_PASSWORD}
  settings:
    settings:
      file_private_path: 'sites/default/files/private'
    databases:
      sparql_default:
        default:
          prefix: ""
          host: ${drupal.sparql.host}
          port: ${drupal.sparql.port}
          namespace: 'Drupal\sparql_entity_storage\Driver\Database\sparql'
          driver: 'sparql'
```

settings.override.php
```
<?php

$databases["sparql_default"] = array('default' => array('prefix' => '','host' => 'sparql','port' => '8890','namespace' => 'Drupal\\sparql_entity_storage\\Driver\\Database\\sparql','driver' => 'sparql'));
```
